"""Add started_at to node_progress

Revision ID: 0a4e95fbc9b6
Revises: 2fb5ef10619c
Create Date: 2026-03-03 15:48:56.780750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4e95fbc9b6'
down_revision: Union[str, None] = '2fb5ef10619c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_progress', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_progress', 'started_at')
    # ### end Alembic commands ###
